#! /bin/bash

# Several requests to issue to a running resty container

BOUND_PORT="${1:-8111}"

# For JWTs - construct them using https://jwt.io although for obvious reasons
# you should never copy a real secret into the website.
#
# Test secret in base64url format for use in the jwt.io form:
# TEST-SECRET_TEST-SECRET_TEST-SECRET_TEST-SECRET_TEST-SECRET_TEST-SECRET_TEST-SECRET_AA
#

# Timestamps used in test tokens:
# 1999999999 - Wed 18 May 04:33:19 BST 2033
# 1700000000 - Tue 14 Nov 22:13:20 GMT 2023
# 1710000000 - Sat  9 Mar 16:00:00 GMT 2024

# Good full token:
# Header: {
#   "alg": "HS256",
#   "typ": "JWT"
# }
# Payload: {
#   "aud": "approov.io",
#   "exp": 1999999999,
#   "iat": 1700000000,
#   "iss": "ApproovAccountID.approov.io",
#   "sub": "approov|ExampleApproovTokenDID==",
#   "ip": "1.2.3.4",
#   "ipk": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJSm4DMcivAwvhM+KNce2C/X26cj3oGyUwWVUPuNuZHtd2qyVsM+0g7qX73Qh0Of6fn10AApLnl8vRQsvx94fZQ==",
#   "did": "ExampleApproovTokenDID=="
# }
#
GOOD_IPK_TOKEN='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcHByb292LmlvIiwiZXhwIjoxOTk5OTk5OTk5LCJpYXQiOjE3MDAwMDAwMDAsImlzcyI6IkFwcHJvb3ZBY2NvdW50SUQuYXBwcm9vdi5pbyIsInN1YiI6ImFwcHJvb3Z8RXhhbXBsZUFwcHJvb3ZUb2tlbkRJRD09IiwiaXAiOiIxLjIuMy40IiwiaXBrIjoiTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSlNtNERNY2l2QXd2aE0rS05jZTJDL1gyNmNqM29HeVV3V1ZVUHVOdVpIdGQycXlWc00rMGc3cVg3M1FoME9mNmZuMTBBQXBMbmw4dlJRc3Z4OTRmWlE9PSIsImRpZCI6IkV4YW1wbGVBcHByb292VG9rZW5ESUQ9PSJ9.hV6xTkGsp9uWwrD-yKkIGTBJawbofJEsuRLw9Qa5YXY'

# B64 DER encoded ASN1 private key that we are using for test
TEST_PRIVATE_KEY="MHcCAQEEIHWZ2Ueq6odQNG+aaYmEbp7C6nujYNGr7nYKK2jqQ2asoAoGCCqGSM49AwEHoUQDQgAEJSm4DMcivAwvhM+KNce2C/X26cj3oGyUwWVUPuNuZHtd2qyVsM+0g7qX73Qh0Of6fn10AApLnl8vRQsvx94fZQ=="
# B64 DER encoded ASN1 public key that we are using for test
TEST_IPK="MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJSm4DMcivAwvhM+KNce2C/X26cj3oGyUwWVUPuNuZHtd2qyVsM+0g7qX73Qh0Of6fn10AApLnl8vRQsvx94fZQ=="

printf "\n\n*** Test1 start - almost minimal, check the method and approov token ***\n"
##############################
# Set test1 specific variables
##############################
TEST1_TARGET_URI="http://0.0.0.0:${BOUND_PORT}/token?param1=value1&param2=value2"
TEST1_SIGNATURE_INPUT='("@method" "approov-token");alg="ecdsa-p256-sha256";created=1744292750;expires=1999999999'
# Message as it should be regenerated by "/token" handler
TEST1_MESSAGE=$(cat <<EOF
"@method": GET
"approov-token": ${GOOD_IPK_TOKEN}
"@signature-params": ${TEST1_SIGNATURE_INPUT}
EOF
)
TEST1_MESSAGE_B64=$(echo -n "${TEST1_MESSAGE}" | base64)

# Print the message we are signing
printf "\n\n*** Message to sign ***\n"
echo -n "${TEST1_MESSAGE_B64}" | base64 --decode
printf "\n\n*** Message to sign SHA256 ***\n"
echo -n "${TEST1_MESSAGE}" | openssl dgst -binary -sha256 | openssl base64 -A
printf "\n\n*** Message to sign (base64) ***\n"
echo "${TEST1_MESSAGE_B64}"

printf "\n\n*** Generate a signature for test ***\n"
TEST1_SIG=$(curl -H "private-key: ${TEST_PRIVATE_KEY}" -H "msg: ${TEST1_MESSAGE_B64}" http://0.0.0.0:${BOUND_PORT}/ipk_message_sign_test)
# if TEST1_SIG reports 404 then give up
if [[ "${TEST1_SIG}" == *"404"* ]]; then
  printf "\n\n*** Failed to generate signature ***\n"
  exit 1
fi
printf "\n\n*** Signature generated ***\n"
echo "${TEST1_SIG}"

printf "\n\n*** Test IPK Verify ***\n"
curl -D- -H "approov-token: ${GOOD_IPK_TOKEN}" -H "signature: install=:${TEST1_SIG}:" -H "signature-input: install=${TEST1_SIGNATURE_INPUT}" "${TEST1_TARGET_URI}"
# if curl receives 200 then record success else failure
if [[ $? -eq 0 ]]; then
  printf "\n\n*** Test1 success ***\n"
else
  printf "\n\n*** Test1 fail ***\n"
fi

printf "\n\n*** Test2 start  - as before but with taget uri ***\n"
##############################
# Set test2 specific variables
##############################
TEST2_TARGET_URI="http://0.0.0.0:${BOUND_PORT}/token?param1=value1&param2=value2"
TEST2_SIGNATURE_INPUT='("@method" "@target-uri" "approov-token");alg="ecdsa-p256-sha256";created=1744292750;expires=1999999999'
# Message as it should be regenerated by "/token" handler
TEST2_MESSAGE=$(cat <<EOF
"@method": GET
"@target-uri": ${TEST2_TARGET_URI}
"approov-token": ${GOOD_IPK_TOKEN}
"@signature-params": ${TEST2_SIGNATURE_INPUT}
EOF
)
TEST2_MESSAGE_B64=$(echo -n "${TEST2_MESSAGE}" | base64)

# Print the message we are signing
printf "\n\n*** Message to sign ***\n"
echo -n "${TEST2_MESSAGE_B64}" | base64 --decode
printf "\n\n*** Message to sign SHA256 ***\n"
echo -n "${TEST2_MESSAGE}" | openssl dgst -binary -sha256 | openssl base64 -A
printf "\n\n*** Message to sign (base64) ***\n"
echo "${TEST2_MESSAGE_B64}"

printf "\n\n*** Generate a signature for test ***\n"
TEST2_SIG=$(curl -H "private-key: ${TEST_PRIVATE_KEY}" -H "msg: ${TEST2_MESSAGE_B64}" http://0.0.0.0:${BOUND_PORT}/ipk_message_sign_test)
# if TEST2_SIG reports 404 then give up
if [[ "${TEST2_SIG}" == *"404"* ]]; then
  printf "\n\n*** Failed to generate signature ***\n"
  exit 1
fi
printf "\n\n*** Signature generated ***\n"
echo "${TEST2_SIG}"

printf "\n\n*** Test IPK Verify ***\n"
curl -D- -H "approov-token: ${GOOD_IPK_TOKEN}" -H "signature: install=:${TEST2_SIG}:" -H "signature-input: install=${TEST2_SIGNATURE_INPUT}" "${TEST2_TARGET_URI}"
# if curl receives 200 then record success else failure
if [[ $? -eq 0 ]]; then
  printf "\n\n*** Test2 success ***\n"
else
  printf "\n\n*** Test2 fail ***\n"
fi

printf "\n\n*** Test3 start - as before but a POST with a body and verified content-digest (string) ***\n"
# ##############################
# # Set test3 specific variables
# ##############################
TEST3_TARGET_URI="http://0.0.0.0:${BOUND_PORT}/token?param1=value1&param2=value2"
TEST3_SIGNATURE_INPUT='("@method" "@target-uri" "approov-token" "content-digest");alg="ecdsa-p256-sha256";created=1744292750;expires=1999999999'
TEST3_MESSAGE_BODY='My test message body'
TEST3_BODY_SHA256_B64=$(echo -n "${TEST3_MESSAGE_BODY}" | openssl dgst -binary -sha256 | openssl base64 -A)

# Message as it should be regenerated by "/token" handler
TEST3_MESSAGE=$(cat <<EOF
"@method": POST
"@target-uri": ${TEST3_TARGET_URI}
"approov-token": ${GOOD_IPK_TOKEN}
"content-digest": sha-256="${TEST3_BODY_SHA256_B64}"
"@signature-params": ${TEST3_SIGNATURE_INPUT}
EOF
)
TEST3_MESSAGE_B64=$(echo -n "${TEST3_MESSAGE}" | base64)

# Print the message we are signing
printf "\n\n*** Message to sign ***\n"
echo -n "${TEST3_MESSAGE_B64}" | base64 --decode
printf "\n\n*** Message to sign SHA256 b64 encoded ***\n"
echo -n "${TEST3_MESSAGE}" | openssl dgst -binary -sha256 | openssl base64 -A
printf "\n\n*** Message to sign (base64) ***\n"
echo "${TEST3_MESSAGE_B64}"

printf "\n\n*** Generate a signature for test ***\n"
TEST3_SIG=$(curl -H "private-key: ${TEST_PRIVATE_KEY}" -H "msg: ${TEST3_MESSAGE_B64}" http://0.0.0.0:${BOUND_PORT}/ipk_message_sign_test)
# if TEST3_SIG reports 404 then give up
if [[ "${TEST3_SIG}" == *"404"* ]]; then
  printf "\n\n*** Failed to generate signature ***\n"
  exit 1
fi
printf "\n\n*** Signature generated ***\n"
echo "${TEST3_SIG}"

printf "\n\n*** Test IPK Verify ***\n"
curl -D- -X POST \
  -H "approov-token: ${GOOD_IPK_TOKEN}" \
  -H "content-digest: sha-256=\"${TEST3_BODY_SHA256_B64}\"" \
  -H "signature: install=:${TEST3_SIG}:" \
  -H "signature-input: install=${TEST3_SIGNATURE_INPUT}" \
  -d "${TEST3_MESSAGE_BODY}" \
  "${TEST3_TARGET_URI}"
# if curl receives 200 then record success else failure
if [[ $? -eq 0 ]]; then
  printf "\n\n*** Test3 success ***\n"
else
  printf "\n\n*** Test3 fail ***\n"
fi

printf "\n\n*** Test4 start - as before but a POST with a body and verified content-digest (byte-sequence) ***\n"
# ##############################
# # Set test4 specific variables
# ##############################
TEST4_TARGET_URI="http://0.0.0.0:${BOUND_PORT}/token?param1=value1&param2=value2"
TEST4_SIGNATURE_INPUT='("@method" "@target-uri" "approov-token" "content-digest");alg="ecdsa-p256-sha256";created=1744292750;expires=1999999999'
TEST4_MESSAGE_BODY='My test message body'
TEST4_BODY_SHA256_B64=$(echo -n "${TEST4_MESSAGE_BODY}" | openssl dgst -binary -sha256 | openssl base64 -A)

# Message as it should be regenerated by "/token" handler
TEST4_MESSAGE=$(cat <<EOF
"@method": POST
"@target-uri": ${TEST4_TARGET_URI}
"approov-token": ${GOOD_IPK_TOKEN}
"content-digest": sha-256=:${TEST4_BODY_SHA256_B64}:
"@signature-params": ${TEST4_SIGNATURE_INPUT}
EOF
)
TEST4_MESSAGE_B64=$(echo -n "${TEST4_MESSAGE}" | base64)

# Print the message we are signing
printf "\n\n*** Message to sign ***\n"
echo -n "${TEST4_MESSAGE_B64}" | base64 --decode
printf "\n\n*** Message to sign SHA256 b64 encoded ***\n"
echo -n "${TEST4_MESSAGE}" | openssl dgst -binary -sha256 | openssl base64 -A
printf "\n\n*** Message to sign (base64) ***\n"
echo "${TEST4_MESSAGE_B64}"

printf "\n\n*** Generate a signature for test ***\n"
TEST4_SIG=$(curl -H "private-key: ${TEST_PRIVATE_KEY}" -H "msg: ${TEST4_MESSAGE_B64}" http://0.0.0.0:${BOUND_PORT}/ipk_message_sign_test)
# if TEST4_SIG reports 404 then give up
if [[ "${TEST4_SIG}" == *"404"* ]]; then
  printf "\n\n*** Failed to generate signature ***\n"
  exit 1
fi
printf "\n\n*** Signature generated ***\n"
echo "${TEST4_SIG}"

printf "\n\n*** Test IPK Verify ***\n"
curl -D- -X POST \
  -H "approov-token: ${GOOD_IPK_TOKEN}" \
  -H "content-digest: sha-256=:${TEST4_BODY_SHA256_B64}:" \
  -H "signature: install=:${TEST4_SIG}:" \
  -H "signature-input: install=${TEST4_SIGNATURE_INPUT}" \
  -d "${TEST4_MESSAGE_BODY}" \
  "${TEST4_TARGET_URI}"
# if curl receives 200 then record success else failure
if [[ $? -eq 0 ]]; then
  printf "\n\n*** Test4 success ***\n"
else
  printf "\n\n*** Test4 fail ***\n"
fi
